### ISSUE TITLE
Проверь на всякий случай

### ISSUE THREAD

**Issue by woodholly** [dragomano/Light-Portal#100]
В лог сыпятся вот такие вот запросы:
```
/index.php?page=ad%2F%2A%2A%2FAND%2F%2A%2A%2F8517%2F%2A%2A%2FIN%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F%28CHAR%28113%29%2BCHAR%28118%29%2BCHAR%28120%29%2BCHAR%28120%29%2BCHAR%28113%29%2B%28SELECT%2F%2A%2A%2F%28CASE%2F%2A%2A%2FWHEN%2F%2A%2A%2F%288517%3D8517%29%2F%2A%2A%2FTHEN%2F%2A%2A%2FCHAR%2849%29%2F%2A%2A%2FELSE%2F%2A%2A%2FCHAR%2848%29%2F%2A%2A%2FEND%29%29%2BCHAR%28113%29%2BCHAR%28113%29%2BCHAR%28107%29%2BCHAR%2898%29%2BCHAR%28113%29%29%29](https://forum-1c.ru/index.php?page=ad%2F%2A%2A%2FAND%2F%2A%2A%2F8517%2F%2A%2A%2FIN%2F%2A%2A%2F%28SELECT%2F%2A%2A%2F%28CHAR%28113%29%2BCHAR%28118%29%2BCHAR%28120%29%2BCHAR%28120%29%2BCHAR%28113%29%2B%28SELECT%2F%2A%2A%2F%28CASE%2F%2A%2A%2FWHEN%2F%2A%2A%2F%288517%3D8517%29%2F%2A%2A%2FTHEN%2F%2A%2A%2FCHAR%2849%29%2F%2A%2A%2FELSE%2F%2A%2A%2FCHAR%2848%29%2F%2A%2A%2FEND%29%29%2BCHAR%28113%29%2BCHAR%28113%29%2BCHAR%28107%29%2BCHAR%2898%29%2BCHAR%28113%29%29%29)
```
Думаю ты знаешь что это, проверь на всякий случай...

**Comment by dragomano** [comment]
Так и не понял, что и где я должен проверить. У меня такой страницы нет. В дистрибутиве по умолчанию идет только страница home. Если у вас эта страница есть, вам её и проверять, хотя скорее всего это какие-нибудь рекламные боты лог засоряют :)

**Comment by woodholly** [comment]
Это попытка sql injection через твой мод

**Comment by dragomano** [comment]
Все запросы стандартные, $_REQUEST обрабатывается самим движком.

**Comment by woodholly** [comment]
А в каком коде мода используется page для запроса страницы из базы ?

**Comment by dragomano** [comment]
Например, [здесь](https://github.com/dragomano/Light-Portal/blob/master/Sources/LightPortal/Entities/Page.php) можно посмотреть. Вообще, в коде везде используется константа LP_PAGE_PARAM, которая по умолчанию равна `page`, но может быть изменена вручную в Integration.php, либо в настройках портала.

**Comment by woodholly** [comment]
Нашел, похоже что всё хорошо, в коде page попадает сюда: alias = {string:alias}, ну а дальше его квотит движок smf, поэтому беспокоиться неочем!
