### ISSUE TITLE
The Plugin "ImageUpload" broke the page plugin

### ISSUE THREAD

**Issue by Darknico** [dragomano/Light-Portal#116]
**Describe the bug** (**Опишите баг**)
After installation the plugin "ImageUpload", the plugin list not work, white page wth error

> Fatal error: Uncaught Error: Value of type null is not callable in /mysite/forum/Sources/LightPortal/Addons/ImageUpload/ImageUpload.php:414 Stack trace: #0 /mysite/forum/Sources/LightPortal/Addons/ImageUpload/ImageUpload.php(59): Bugo\LightPortal\Addons\ImageUpload\ImageUpload->prepareTable() #1 /mysite/forum/Sources/LightPortal/AddonHandler.php(103): Bugo\LightPortal\Addons\ImageUpload\ImageUpload->addSettings() #2 /mysite/forum/Sources/LightPortal/Helper.php(96): Bugo\LightPortal\AddonHandler->run() #3 /mysite/forum/Sources/LightPortal/Areas/PluginArea.php(84): Bugo\LightPortal\Areas\PluginArea->hook() #4 /mysite/forum/Sources/Subs.php(5934): Bugo\LightPortal\Areas\PluginArea->main() #5 /mysite/forum/Sources/LightPortal/Utils/SMFTrait.php(262): call_helper() #6 /mysite/forum/Sources/LightPortal/Areas/ConfigArea.php(251): Bugo\LightPortal\Areas\ConfigArea->callHelper() #7 /mysite/forum/Sources/LightPortal/Areas/ConfigArea.php(233): Bugo\LightPortal\Areas\ConfigArea->loadGeneralSettingParameters() #8 /mysite/forum/Sources/Admin.php(499): Bugo\LightPortal\Areas\ConfigArea->pluginAreas() #9 /mysite/forum/index.php(198): AdminMain() #10 {main} thrown in /mysite/forum/Sources/LightPortal/Addons/ImageUpload/ImageUpload.php on line 414

Error log:

> Undefined array key "db_list_tables"

**To Reproduce** (**Как воспроизвести, по шагам**)
1. install "ImageUpload"
2. Go in plugin list

**Expected behavior** (**Ожидаемое поведение — что хотели получить вместо бага**)
No issue in plugin list :)

**Environment**
- Version/Git revision: 2.1 beta
- Database Type: Mysql
- Database Version: 5.7.28
- PHP Version:  8.0.14
- SMF Version: 2.0.13

**Comment by dragomano** [comment]
Move `$this->dbExtend('packages');` to the beginning of prepareTable() method. Like this:
```php
	private function prepareTable()
	{
		$tables = [];

		$this->dbExtend('packages');

		if (! empty($this->smcFunc['db_list_tables'](false, $this->db_prefix . 'lp_attachments')))
			return;
```

P. S. SMF 2.0.13? Did you mean 2.1.3?

**Comment by Darknico** [comment]
Ups sorry, yes yes 2.1.3 ;D

Solved the issue after this change ;)

**Comment by dragomano** [comment]
Ok, I've re-uploaded the plugin package.
