### ISSUE TITLE
Single quote issue in title block/page

### ISSUE THREAD

**Issue by Darknico** [dragomano/Light-Portal#158]
**Describe the bug** (**Опишите баг**)
The single quote in title block create an issue after save, impossible re-edit the title, hide the field

**To Reproduce** (**Как воспроизвести, по шагам**)
1. Go in to block (or page)
2. Added a single quote
4. Save

**Expected behavior** (**Ожидаемое поведение — что хотели получить вместо бага**)
Possibility to edit the title

**Screenshots**
![immagine](https://github.com/dragomano/Light-Portal/assets/3503100/e4033295-86b3-47b0-9c21-28a36e6b1d61)

**Environment**
- Version/Git revision: 2.4.2
- Database Type: MySQL
- Database Version: 5.7.28
- PHP Version: 8.1.1
- SMF Version: 2.1.4

**Comment by Darknico** [comment]
Sorry, checked after in page, same issue, update the bug

**Comment by dragomano** [comment]
As a temporary solution, make these changes

in Areas/PageArea.php:

find
```php
	foreach ($this->context['languages'] as $lang) {
		$this->context['lp_page']['title'][$lang['filename']] = $post_data['title_' . $lang['filename']] ?? $this->context['lp_page']['title'][$lang['filename']] ?? '';
	}
```

replace with
```php
	foreach ($this->context['languages'] as $lang) {
		$this->context['lp_page']['title'][$lang['filename']] = $post_data['title_' . $lang['filename']] ?? $this->context['lp_page']['title'][$lang['filename']] ?? '';
		$this->context['lp_page']['title'][$lang['filename']] = $this->smcFunc['htmlspecialchars']($this->context['lp_page']['title'][$lang['filename']]);
	}
```

and in Areas/BlockArea.php:

find
```php
	foreach ($this->context['languages'] as $lang) {
		$this->context['lp_block']['title'][$lang['filename']] = $post_data['title_' . $lang['filename']] ?? $this->context['lp_block']['title'][$lang['filename']] ?? '';
	}
```

replace with
```php
	foreach ($this->context['languages'] as $lang) {
		$this->context['lp_block']['title'][$lang['filename']] = $post_data['title_' . $lang['filename']] ?? $this->context['lp_block']['title'][$lang['filename']] ?? '';
		$this->context['lp_block']['title'][$lang['filename']] = $this->smcFunc['htmlspecialchars']($this->context['lp_block']['title'][$lang['filename']]);
	}
```

**Comment by Darknico** [comment]
I test the temporaly fix and work.
Not beatiful coverted in &amp;#039; but ok for now :D

**Comment by dragomano** [comment]
That's why it's temporary :)

**Comment by dragomano** [comment]
Ok, undo previous changes, open ManageBlocks.template.php

find
```php
$titles .= ', title_' . $lang['filename'] . ': \'' . ($context['lp_block']['title'][$lang['filename']] ?? '') . '\'';
```

replace with
```php
$titles .= ', title_' . $lang['filename'] . ': `' . ($context['lp_block']['title'][$lang['filename']] ?? '') . '`';
```

Сделайте аналогичные изменения в ManagePages.template.php

**Comment by Darknico** [comment]
Yes, work correctly 👍🏻 

in ManagePages.template.php
`$titles .= ', title_' . $lang['filename'] . ': `' . ($context['lp_page']['title'][$lang['filename']] ?? '') . '`';`
