### ISSUE TITLE
Кликабельный заголовок блока

### ISSUE THREAD

**Issue by woodholly** [dragomano/Light-Portal#198]
Сделайте пожалуйста, чтобы можно было сделать заголовок блока ссылкой.

**Comment by dragomano** [comment]
Примеры использования?

**Comment by woodholly** [comment]
Последние темы ссылкой, для перехода в соответвствующий раздел, лучше по ссылке заданной в настройках блока.

**Comment by dragomano** [comment]
Как-то так:

![sshot-18](https://github.com/dragomano/Light-Portal/assets/229402/d0689eb7-1525-4714-a417-e5b1fd1a06c3)

**Comment by dragomano** [comment]
Стоит ли это делать для всех блоков или просто для некоторых, типа Последних тем, сообщений и т. п.?

**Comment by woodholly** [comment]
Для других блоков наверное не нужно, не придумал как использовать..

**Comment by Darknico** [comment]
> Стоит ли это делать для всех блоков или просто для некоторых, типа Последних тем, сообщений и т. п.?

Interesting feature, for me is a good idea for all block (enabled or not)
