### ISSUE TITLE
CR LF repository bug ?

### ISSUE THREAD

**Issue by woodholly** [dragomano/Light-Portal#27]
У тебя какой-то глюк в репозитории, я такое вижу впервые.
После git clone в linux, появляется файл Themes/default/languages/LightPortal/index.php c незакоммиченными изменениями, я думаю это из-за какого-то конфликта с CR-LF в этом файле. Перепробовал всё, ничего не сработало. Работать с репозиторием невозможно. Как это исправить ?

Как проверить: сделай git clone https://github.com/dragomano/Light-Portal в Linux Debian Buster, затем cd Light-Portal; git status

**Comment by woodholly** [comment]
По идее должен помочь dos2unix Themes/default/languages/LightPortal/index.php

**Comment by dragomano** [comment]
Пересохранил в LF в dev ветке, может поможет. Linux использовать пока нет возможности.

**Comment by woodholly** [comment]
Помогло, но в мастер нужно добавить ASAP так как сразу после clone работать невозможно.
