### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by woodholly** [dragomano/Light-Portal#31]
**Describe the bug** (**Опишите баг**)
This commit: 8407cc48bd7dd1e3c6d495710c8ce42753595516
makes update from older versions impossible without reading the code and applying database modifications manually, why you did that ?

**Comment by woodholly** [comment]
This includes all subsequent modifications to database.php, like 720b6ca9aae987d6c8189e83fbd84504f33a3512

**Comment by dragomano** [comment]
How to upgrade (if you want to save blocks and pages):

0) Upgrade to v1.8.2 (just copy the contents of the Sources directory from the archive over the same directory on your server, replacing the files).
1) Make an export of pages and blocks.
2) Delete the portal completely, including the tables added to the database.
3) Install the new version.
4) Make import pages and blocks.

**Comment by woodholly** [comment]
But how to export and import other portal settings ?

**Comment by dragomano** [comment]
The settings of any modification are stored in the database, in the {db_prefix}settings. This mod does not remove them on uninstalling.

**Comment by woodholly** [comment]
Good!
Stuck on this error after upgrade:
```
Unable to load the 'ads_block_above' template.
```
Version: master branch

**Comment by dragomano** [comment]
What line is this error? Do you have function `template_ads_block_above` in /Sources/LightPortal/addons/AdsBlock/template.php?

**Comment by woodholly** [comment]
This happens on page: index.php?action=admin;area=lp_blocks
Backtrace:
```
    #0: loadSubTemplate()
    /Sources/Subs.php line 3913
    #1: template_header()
    /Sources/Subs.php line 3497
    #2: obExit()
    /index.php line 176
```

Yes:
```
Sources/LightPortal/addons/AdsBlock/Template.php:
function template_ads_block_above() {}
```

**Comment by woodholly** [comment]
RC3

**Comment by dragomano** [comment]
Make export of ads blocks and attach here.

**Comment by woodholly** [comment]
This happens after full uninstall with table removal, so there are no blocks. I can't import nor export because of this bug.

**Comment by woodholly** [comment]
Can this be related to file renaming ?
Old:
/Sources/LightPortal/addons/AdsBlock/template.php
New:
/Sources/LightPortal/addons/AdsBlock/Template.php

**Comment by dragomano** [comment]
What if trying to clear the cache, or remove "AdsBlock" from the setting `lp_enabled_plugins` (smf_settings table in the database).
Also, remove all the addons directory fully, then upload this directory from the new package.

**Comment by woodholly** [comment]
Renaming Template.php to template.php solves that bug
