### ISSUE TITLE
A different label for menu

### ISSUE THREAD

**Issue by Darknico** [dragomano/Light-Portal#81]
**Is your feature request related to a problem? Please describe.** (**Опишите, зачем вам эта фича**)
No, it only is a suggestion

**Describe the solution you'd like** (**Опишите желаемое решение**)
The possibility to change the label for Portal and Forum
![immagine](https://user-images.githubusercontent.com/3503100/161931544-7fd4c486-9e82-4eb4-a3fa-b8257f92a5ca.png)
not by translation, but by setting in admin area, because each mod update, replace all customization for these labels

**Comment by dragomano** [comment]
I decided it was easier to implement this feature into an existing plugin than to add new options to the mod itself :)

**Comment by Darknico** [comment]
It is a good idea, I tested and work correclty :)
Only a little suggestion:

![immagine](https://user-images.githubusercontent.com/3503100/162384918-26331e13-7c91-4f2a-9f28-51cedea9b630.png)

In the navigation, use the old label

**Comment by dragomano** [comment]
Should the new label be displayed there too?

**Comment by Darknico** [comment]
For me, yes, it is more correct.
The frontpage now I rename in "Home".

Does it make sense to you?

**Comment by dragomano** [comment]
Ok, add this code to MainMenu.php:
```php
	public function frontCustomTemplate()
	{
		if (! empty($this->context['lp_main_menu_addon_portal_langs'][$this->user_info['language']]) && ! empty($this->context['linktree'][1]))
			$this->context['linktree'][1]['name'] = $this->context['lp_main_menu_addon_portal_langs'][$this->user_info['language']];
	}
```

**Comment by Darknico** [comment]
Missing in the init the hook :)
`add_integration_function('integrate_menu_buttons', __CLASS__ . '::frontCustomTemplate#', false, __FILE__);`

work correctly 
![immagine](https://user-images.githubusercontent.com/3503100/162394529-659e23fb-418c-484a-8b11-4c641f812cc5.png)

**Comment by dragomano** [comment]
It is a portal hook, you shouldn't add it via add_integration_function. It is enough to add a hook name in the plugin file.

**Comment by Darknico** [comment]
Sorry, I didn't understand where to add it.
I'm not very experienced with hooks (and php knowledge is basic)
