### ISSUE TITLE
Only english language supported, no other language files in repository

### ISSUE THREAD

**Issue by woodholly** [dragomano/Light-Portal#97]
Only english is available, although I see other language files at the [custom.simplemachines.org website ...
](https://custom.simplemachines.org/index.php?mod=4244)

**Comment by dragomano** [comment]
Other languages are on [Crowdin](https://crowdin.com/project/light-portal)

**Comment by woodholly** [comment]
Cool! Is there any command to pull all translations into repository instead of downloading them one by one ?

**Comment by dragomano** [comment]
You can get all translations via this link - https://crowdin.com/backend/download/project/light-portal.zip
